apiVersion: apps/v1
kind: Deployment
metadata:
  name: clouddeploy-vue
  labels:
    app: vue-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vue-app
  template:
    metadata:
      labels:
        app: vue-app
    spec:
      containers:
      - name: vue-app
        image: vue-clouddeploy-image
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: clouddeploy-vue-service
spec:
  selector:
    app: myapp
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer