apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-preprod

commonLabels:
  environment: preprod

bases:
- ../../base/k8s/deployments
- ../../base/k8s/services

resources:
- namespace.yaml