# Build and tag using commit sha

steps:

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '-t', 'gcr.io/$PROJECT_ID/vue-clouddeploy-image:${COMMIT_SHA}', '-f', 'Dockerfile.vue']


# Push the container image


- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/vue-clouddeploy-image:${COMMIT_SHA}']
# Create release in Google Cloud Deploy


- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
    [
      "deploy", "releases", "create", "rel-${SHORT_SHA}",
      "--delivery-pipeline", "vue-app",
      "--region", "europe-west2",
      "--annotations", "commitId=${REVISION_ID}",
      "--images", "vue-clouddeploy-image=gcr.io/$PROJECT_ID/vue-clouddeploy-image:${COMMIT_SHA}"
    ]
